name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        working-directory: ./webui

      - name: Build the package
        run: npm run build
        working-directory: ./webui

      - name: Bump version and publish
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm version patch
          npm publish
        working-directory: ./webui
