name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write # Allow committing version updates

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        working-directory: ./webui

      - name: Build the package
        run: npm run build
        working-directory: ./webui

      - name: Bump version
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npm version patch
        working-directory: ./webui

      - name: Commit and push version update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Bump version to $(jq -r .version < package.json)"
          git push origin master
        working-directory: ./webui

      - name: Publish to GitHub Packages
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npm publish
        working-directory: ./webui
